[package]
name = "drumbot"
version = "0.1.0"
authors = ["Frixu <frixu@frixu.me>"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
rodio = "0.9.0"
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"